[project]
name = "logir"
version = "0.1.0"
description = "Example repo for rigol-ds1054z library"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "rigol-ds1054z[usb]>=0.2.3",
]
